CREATE TABLE BOARD 
(
  ID NUMBER NOT NULL 
, TITLE VARCHAR2(100 BYTE) NOT NULL 
, CONTENT CLOB NOT NULL 
, HIT NUMBER 
, IMG BLOB 
, CREATED_AT DATE 
, CREATED_BY VARCHAR2(20 BYTE) 
, CONSTRAINT BOARD_UPK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BOARD_UPK ON BOARD (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL 
LOB (CONTENT) STORE AS SYS_LOB0000022257C00003$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
) 	
LOB (IMG) STORE AS SYS_LOB0000022257C00005$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

COMMENT ON COLUMN BOARD.ID IS 'index';

COMMENT ON COLUMN BOARD.CONTENT IS '2GB';
------------------------------------------------------------------------
CREATE TABLE MEMBER 
(
  ID NUMBER NOT NULL 
, USERID VARCHAR2(20 BYTE) NOT NULL 
, USERNAME VARCHAR2(20 BYTE) NOT NULL 
, USERPW VARCHAR2(250 BYTE) NOT NULL 
, USERPHONE VARCHAR2(20 BYTE) 
, CREATED_AT DATE 
, CREATED_BY VARCHAR2(20 BYTE) 
, CONSTRAINT MEMBER_UPK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MEMBER_UPK ON MEMBER (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_USERID_UK UNIQUE 
(
  USERID 
)
USING INDEX 
(
    CREATE UNIQUE INDEX MEMBER_USERID_UK ON MEMBER (USERID ASC) 
    LOGGING 
    TABLESPACE USERS 
    PCTFREE 10 
    INITRANS 2 
    STORAGE 
    ( 
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS UNLIMITED 
      BUFFER_POOL DEFAULT 
    ) 
    NOPARALLEL 
)
 ENABLE;

COMMENT ON COLUMN MEMBER.ID IS 'index';

COMMENT ON COLUMN MEMBER.USERPW IS 'password';
---------------------------------------------------------------------
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
---------------------------------------------------------------------
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;

